In [ ]:
import pandas as pd

In [ ]:
obesity = pd.read_csv('CHIS_obesity.csv')
counties = ['Butte','Shasta', 'Humboldt', 'Siskiyou, Lassen, Trinity, Modoc, Plumas, Sierra', 'Mendocino', 'Lake', 'Tehema, Glenn, Colusa', 'Sutter', 'Yuba', 'Nevada', 'Tuolumne, Calaveras, Amador, Inyo, Mariposa, Mono, Alpine', 'Santa Clara', 'Alameda', 'Contra Costa', 'San Francisco', 'San Mateo', 'Sonoma', 'Solano', 'Marin', 'Napa', 'Sacramento', 'Placer', 'Yolo', 'El Dorado', 'Fresno', 'Kern', 'San Joaquin', 'Stanislaus', 'Tulare', 'Merced', 'Kings', 'Madera', 'Ventura', 'Santa Barbara', 'Satna Cruz', 'San Luis Obispo', 'Monterey', 'San Benito', 'Los Angeles', 'Orange', 'San Diego', 'San Bernadino', 'Riverside', 'Imperial', 'All']
obesity.reset_index(drop=True, inplace=True)
years = [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
obesity

,Unnamed: 0,Unnamed: 1,Butte,Butte.1,Shasta,Shasta.1,Humboldt,Humboldt.1,"Del Norte, Siskiyou, Lassen, Trinity, Modoc, Plumas, Sierra","Del Norte, Siskiyou, Lassen, Trinity, Modoc, Plumas, Sierra.1",...,San Diego,San Diego.1,San Bernardino,San Bernardino.1,Riverside,Riverside.1,Imperial,Imperial.1,All,All.1
0,BMI,Year,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
1,0 - 18.49 (Underweight,2011,3.1*,"5,000",2.1*,"3,000",-,-,5.0*,"6,000",...,2.20%,"49,000",1.1*,"15,000",1.2*,"18,000",-,-,1.60%,"448,000"
2,0 - 18.49 (Underweight,2012,2.1*,"4,000",-,-,1.1*,"1,000",4.2*,"5,000",...,1.50%,"35,000",1.0*,"15,000",2.40%,"39,000",0.4*,"1,000",1.60%,"448,000"
3,0 - 18.49 (Underweight,2013,-,-,1.0*,"1,000",-,-,0.6*,"1,000",...,1.20%,"29,000",1.0*,"14,000",2.3*,"37,000",1.1*,"1,000",1.30%,"359,000"
4,0 - 18.49 (Underweight,2014,-,-,-,-,-,-,-,-,...,2.2*,"52,000",1.1*,"16,000",0.3*,"5,000",2.2*,"3,000",1.60%,"460,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Total,2019,100.00%,"166,000",100.00%,"138,000",100.00%,"104,000",100.00%,"94,000",...,100.00%,"2,441,000",100.00%,"1,566,000",100.00%,"1,792,000",100.00%,"125,000",100.00%,"29,669,000"
62,Total,2020,100.00%,"162,000",100.00%,"132,000",100.00%,"101,000",100.00%,"111,000",...,100.00%,"2,440,000",100.00%,"1,574,000",100.00%,"1,812,000",100.00%,"124,000",100.00%,"29,685,000"
63,Total,2021,100.00%,"158,000",100.00%,"136,000",100.00%,"100,000",100.00%,"104,000",...,100.00%,"2,425,000",100.00%,"1,555,000",100.00%,"1,798,000",100.00%,"122,000",100.00%,"29,650,000"
64,Total,2022,100.00%,"161,000",100.00%,"140,000",100.00%,"103,000",100.00%,"107,000",...,100.00%,"2,413,000",100.00%,"1,582,000",100.00%,"1,822,000",100.00%,"118,000",100.00%,"29,561,000"
65,Total,2023,100.00%,"162,000",100.00%,"139,000",100.00%,"104,000",100.00%,"103,000",...,100.00%,"2,373,000",100.00%,"1,572,000",100.00%,"1,838,000",100.00%,"120,000",100.00%,"29,211,000"

In [ ]:
df = []

for i in counties:
  for year in years:
    df.append([i, year])

df = pd.DataFrame(df, columns=['County', 'Year'])
df

    County  Year
0    Butte  2011
1    Butte  2012
2    Butte  2013
3    Butte  2014
4    Butte  2015
..     ...   ...
580    All  2019
581    All  2020
582    All  2021
583    All  2022
584    All  2023

[585 rows x 2 columns]

In [ ]:
new_header = obesity.iloc[0] #grab the first row for the header
obesity = obesity[1:] #take the data less the header row
obesity.columns = new_header
obesity

,BMI,Year,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
1,0 - 18.49 (Underweight,2011,3.1*,"5,000",2.1*,"3,000",-,-,5.0*,"6,000",...,2.20%,"49,000",1.1*,"15,000",1.2*,"18,000",-,-,1.60%,"448,000"
2,0 - 18.49 (Underweight,2012,2.1*,"4,000",-,-,1.1*,"1,000",4.2*,"5,000",...,1.50%,"35,000",1.0*,"15,000",2.40%,"39,000",0.4*,"1,000",1.60%,"448,000"
3,0 - 18.49 (Underweight,2013,-,-,1.0*,"1,000",-,-,0.6*,"1,000",...,1.20%,"29,000",1.0*,"14,000",2.3*,"37,000",1.1*,"1,000",1.30%,"359,000"
4,0 - 18.49 (Underweight,2014,-,-,-,-,-,-,-,-,...,2.2*,"52,000",1.1*,"16,000",0.3*,"5,000",2.2*,"3,000",1.60%,"460,000"
5,0 - 18.49 (Underweight,2015,1.1*,"2,000",-,-,2.4*,"3,000",-,-,...,1.8*,"43,000",1.9*,"29,000",2.4*,"40,000",2.0*,"2,000",2.00%,"583,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Total,2019,100.00%,"166,000",100.00%,"138,000",100.00%,"104,000",100.00%,"94,000",...,100.00%,"2,441,000",100.00%,"1,566,000",100.00%,"1,792,000",100.00%,"125,000",100.00%,"29,669,000"
62,Total,2020,100.00%,"162,000",100.00%,"132,000",100.00%,"101,000",100.00%,"111,000",...,100.00%,"2,440,000",100.00%,"1,574,000",100.00%,"1,812,000",100.00%,"124,000",100.00%,"29,685,000"
63,Total,2021,100.00%,"158,000",100.00%,"136,000",100.00%,"100,000",100.00%,"104,000",...,100.00%,"2,425,000",100.00%,"1,555,000",100.00%,"1,798,000",100.00%,"122,000",100.00%,"29,650,000"
64,Total,2022,100.00%,"161,000",100.00%,"140,000",100.00%,"103,000",100.00%,"107,000",...,100.00%,"2,413,000",100.00%,"1,582,000",100.00%,"1,822,000",100.00%,"118,000",100.00%,"29,561,000"
65,Total,2023,100.00%,"162,000",100.00%,"139,000",100.00%,"104,000",100.00%,"103,000",...,100.00%,"2,373,000",100.00%,"1,572,000",100.00%,"1,838,000",100.00%,"120,000",100.00%,"29,211,000"

In [ ]:
obesity
increased_risk = obesity[obesity['BMI'] == '23.0 - 27.49 (Increased risk']
obese = obesity[obesity['BMI'] == '27.5 or higher (Higher high risk']
increased_risk

,BMI,Year,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
27,23.0 - 27.49 (Increased risk,2011,35.60%,"61,000",41.20%,"56,000",38.80%,"40,000",32.40%,"36,000",...,39.20%,"878,000",33.10%,"475,000",32.70%,"509,000",33.90%,"40,000",36.20%,"9,858,000"
28,23.0 - 27.49 (Increased risk,2012,36.50%,"62,000",42.90%,"59,000",26.80%,"28,000",34.20%,"37,000",...,38.80%,"901,000",38.20%,"551,000",32.10%,"511,000",21.40%,"24,000",36.20%,"10,062,000"
29,23.0 - 27.49 (Increased risk,2013,32.40%,"55,000",37.50%,"51,000",33.50%,"35,000",33.20%,"37,000",...,38.60%,"908,000",32.20%,"470,000",35.50%,"573,000",22.20%,"26,000",36.90%,"10,394,000"
30,23.0 - 27.49 (Increased risk,2014,37.90%,"66,000",41.10%,"57,000",40.90%,"42,000",43.80%,"48,000",...,36.10%,"857,000",37.80%,"561,000",35.40%,"586,000",35.00%,"41,000",36.20%,"10,339,000"
31,23.0 - 27.49 (Increased risk,2015,38.50%,"68,000",27.80%,"39,000",35.00%,"37,000",27.8*,"31,000",...,34.80%,"843,000",38.20%,"577,000",31.30%,"533,000",31.90%,"38,000",34.40%,"10,012,000"
32,23.0 - 27.49 (Increased risk,2016,41.30%,"73,000",38.80%,"54,000",24.30%,"26,000",36.00%,"40,000",...,34.00%,"832,000",29.10%,"447,000",35.00%,"606,000",29.00%,"35,000",35.90%,"10,562,000"
33,23.0 - 27.49 (Increased risk,2017,32.60%,"61,000",37.20%,"50,000",42.20%,"42,000",31.70%,"33,000",...,37.60%,"910,000",35.80%,"549,000",33.60%,"585,000",27.4*,"33,000",36.10%,"10,637,000"
34,23.0 - 27.49 (Increased risk,2018,33.40%,"55,000",28.60%,"40,000",30.80%,"29,000",33.70%,"35,000",...,35.00%,"853,000",31.90%,"495,000",34.50%,"610,000",25.10%,"31,000",35.70%,"10,597,000"
35,23.0 - 27.49 (Increased risk,2019,32.60%,"54,000",30.30%,"42,000",31.30%,"33,000",31.80%,"30,000",...,33.80%,"825,000",33.00%,"516,000",33.40%,"598,000",26.10%,"32,000",35.20%,"10,455,000"
36,23.0 - 27.49 (Increased risk,2020,32.00%,"52,000",36.00%,"48,000",32.00%,"32,000",42.80%,"47,000",...,36.20%,"883,000",36.20%,"570,000",31.90%,"578,000",35.50%,"44,000",35.30%,"10,489,000"
37,23.0 - 27.49 (Increased risk,2021,38.70%,"61,000",41.10%,"56,000",29.70%,"30,000",28.60%,"30,000",...,37.30%,"905,000",33.00%,"512,000",31.20%,"561,000",30.50%,"37,000",35.00%,"10,378,000"
38,23.0 - 27.49 (Increased risk,2022,36.00%,"58,000",41.80%,"58,000",39.00%,"40,000",30.90%,"33,000",...,38.60%,"933,000",32.70%,"517,000",31.50%,"574,000",28.00%,"33,000",35.20%,"10,416,000"
39,23.0 - 27.49 (Increased risk,2023,30.80%,"50,000",28.60%,"40,000",34.50%,"36,000",30.10%,"31,000",...,37.70%,"895,000",31.40%,"493,000",33.30%,"613,000",21.80%,"26,000",34.40%,"10,039,000"

In [ ]:
obese = obese.drop(obese.columns[:2], axis = 1)
obese
increased_risk = increased_risk.drop(increased_risk.columns[:2], axis = 1)
increased_risk

,%,Population,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
27,35.60%,"61,000",41.20%,"56,000",38.80%,"40,000",32.40%,"36,000",34.40%,"23,000",...,39.20%,"878,000",33.10%,"475,000",32.70%,"509,000",33.90%,"40,000",36.20%,"9,858,000"
28,36.50%,"62,000",42.90%,"59,000",26.80%,"28,000",34.20%,"37,000",35.50%,"24,000",...,38.80%,"901,000",38.20%,"551,000",32.10%,"511,000",21.40%,"24,000",36.20%,"10,062,000"
29,32.40%,"55,000",37.50%,"51,000",33.50%,"35,000",33.20%,"37,000",44.50%,"30,000",...,38.60%,"908,000",32.20%,"470,000",35.50%,"573,000",22.20%,"26,000",36.90%,"10,394,000"
30,37.90%,"66,000",41.10%,"57,000",40.90%,"42,000",43.80%,"48,000",42.00%,"28,000",...,36.10%,"857,000",37.80%,"561,000",35.40%,"586,000",35.00%,"41,000",36.20%,"10,339,000"
31,38.50%,"68,000",27.80%,"39,000",35.00%,"37,000",27.8*,"31,000",34.40%,"23,000",...,34.80%,"843,000",38.20%,"577,000",31.30%,"533,000",31.90%,"38,000",34.40%,"10,012,000"
32,41.30%,"73,000",38.80%,"54,000",24.30%,"26,000",36.00%,"40,000",23.50%,"16,000",...,34.00%,"832,000",29.10%,"447,000",35.00%,"606,000",29.00%,"35,000",35.90%,"10,562,000"
33,32.60%,"61,000",37.20%,"50,000",42.20%,"42,000",31.70%,"33,000",45.90%,"30,000",...,37.60%,"910,000",35.80%,"549,000",33.60%,"585,000",27.4*,"33,000",36.10%,"10,637,000"
34,33.40%,"55,000",28.60%,"40,000",30.80%,"29,000",33.70%,"35,000",40.80%,"30,000",...,35.00%,"853,000",31.90%,"495,000",34.50%,"610,000",25.10%,"31,000",35.70%,"10,597,000"
35,32.60%,"54,000",30.30%,"42,000",31.30%,"33,000",31.80%,"30,000",34.20%,"25,000",...,33.80%,"825,000",33.00%,"516,000",33.40%,"598,000",26.10%,"32,000",35.20%,"10,455,000"
36,32.00%,"52,000",36.00%,"48,000",32.00%,"32,000",42.80%,"47,000",39.00%,"26,000",...,36.20%,"883,000",36.20%,"570,000",31.90%,"578,000",35.50%,"44,000",35.30%,"10,489,000"
37,38.70%,"61,000",41.10%,"56,000",29.70%,"30,000",28.60%,"30,000",30.90%,"22,000",...,37.30%,"905,000",33.00%,"512,000",31.20%,"561,000",30.50%,"37,000",35.00%,"10,378,000"
38,36.00%,"58,000",41.80%,"58,000",39.00%,"40,000",30.90%,"33,000",29.90%,"21,000",...,38.60%,"933,000",32.70%,"517,000",31.50%,"574,000",28.00%,"33,000",35.20%,"10,416,000"
39,30.80%,"50,000",28.60%,"40,000",34.50%,"36,000",30.10%,"31,000",33.90%,"24,000",...,37.70%,"895,000",31.40%,"493,000",33.30%,"613,000",21.80%,"26,000",34.40%,"10,039,000"

In [ ]:
def strip_character_from_dataframe(df, char_to_strip):
    return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)

# Call the function to remove the character 'a'

In [ ]:
def strip_chars(df):
  df = strip_character_from_dataframe(df, '%')
  df = strip_character_from_dataframe(df, '*')
  df = strip_character_from_dataframe(df, ',')
  df = df.replace('-', 0)
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)
  return df

In [ ]:
obese = strip_chars(obese)
increased_risk = strip_chars(increased_risk)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
obese = obese.astype(float)
increased_risk = increased_risk.astype(float)
obese

,%,Population,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
40,42.9,73000.0,40.5,55000.0,43.7,45000.0,46.5,52000.0,37.8,25000.0,...,36.0,806000.0,50.5,725000.0,44.6,694000.0,53.0,62000.0,40.6,11048000.0
41,37.3,64000.0,42.8,59000.0,48.2,50000.0,49.4,54000.0,37.6,25000.0,...,37.1,861000.0,48.3,696000.0,47.2,750000.0,62.0,71000.0,40.2,11163000.0
42,39.9,68000.0,38.8,53000.0,44.6,46000.0,46.5,51000.0,35.0,24000.0,...,37.3,875000.0,53.1,774000.0,41.5,670000.0,64.7,74000.0,40.6,11424000.0
43,46.8,82000.0,42.6,59000.0,45.5,47000.0,38.5,43000.0,42.3,29000.0,...,38.5,915000.0,50.8,753000.0,45.1,746000.0,53.3,62000.0,42.8,12227000.0
44,45.6,80000.0,46.2,64000.0,43.0,45000.0,46.6,52000.0,32.7,22000.0,...,40.6,985000.0,47.6,720000.0,51.1,869000.0,57.4,69000.0,43.7,12709000.0
45,35.1,62000.0,42.5,59000.0,43.4,46000.0,48.6,53000.0,56.5,39000.0,...,42.6,1042000.0,51.8,794000.0,49.0,850000.0,58.6,71000.0,43.2,12690000.0
46,46.5,86000.0,37.0,49000.0,37.7,38000.0,49.9,52000.0,36.9,24000.0,...,36.7,887000.0,46.2,709000.0,46.4,808000.0,58.4,71000.0,40.1,11805000.0
47,44.4,73000.0,54.8,78000.0,41.1,39000.0,51.6,53000.0,34.0,25000.0,...,39.7,966000.0,47.1,731000.0,48.8,864000.0,59.1,72000.0,40.3,11983000.0
48,43.0,71000.0,54.0,75000.0,38.1,40000.0,48.9,46000.0,48.4,35000.0,...,41.2,1006000.0,50.6,793000.0,49.4,885000.0,59.2,74000.0,42.0,12457000.0
49,41.8,68000.0,46.9,62000.0,43.6,44000.0,35.5,39000.0,44.0,29000.0,...,38.5,939000.0,48.6,764000.0,47.8,867000.0,49.5,61000.0,42.3,12550000.0
50,36.3,57000.0,41.6,57000.0,42.3,42000.0,40.1,42000.0,38.8,27000.0,...,36.6,887000.0,50.3,783000.0,49.0,880000.0,55.9,68000.0,42.3,12529000.0
51,42.0,68000.0,40.1,56000.0,42.9,44000.0,52.7,57000.0,49.5,34000.0,...,35.7,862000.0,50.9,805000.0,51.6,941000.0,59.4,70000.0,42.4,12548000.0
52,48.5,79000.0,49.8,69000.0,46.3,48000.0,41.5,43000.0,46.3,33000.0,...,36.4,864000.0,52.0,818000.0,49.7,915000.0,55.3,66000.0,42.8,12514000.0

In [ ]:
obese = obese.reset_index(drop=True)

increased_risk = increased_risk.reset_index(drop = True)

In [ ]:
ob_ir = obese+increased_risk
ob_ir

,%,Population,%,Population,%,Population,%,Population,%,Population,...,%,Population,%,Population,%,Population,%,Population,%,Population
0,78.5,134000.0,81.7,111000.0,82.5,85000.0,78.9,88000.0,72.2,48000.0,...,75.2,1684000.0,83.6,1200000.0,77.3,1203000.0,86.9,102000.0,76.8,20906000.0
1,73.8,126000.0,85.7,118000.0,75.0,78000.0,83.6,91000.0,73.1,49000.0,...,75.9,1762000.0,86.5,1247000.0,79.3,1261000.0,83.4,95000.0,76.4,21225000.0
2,72.3,123000.0,76.3,104000.0,78.1,81000.0,79.7,88000.0,79.5,54000.0,...,75.9,1783000.0,85.3,1244000.0,77.0,1243000.0,86.9,100000.0,77.5,21818000.0
3,84.7,148000.0,83.7,116000.0,86.4,89000.0,82.3,91000.0,84.3,57000.0,...,74.6,1772000.0,88.6,1314000.0,80.5,1332000.0,88.3,103000.0,79.0,22566000.0
4,84.1,148000.0,74.0,103000.0,78.0,82000.0,74.4,83000.0,67.1,45000.0,...,75.4,1828000.0,85.8,1297000.0,82.4,1402000.0,89.3,107000.0,78.1,22721000.0
5,76.4,135000.0,81.3,113000.0,67.7,72000.0,84.6,93000.0,80.0,55000.0,...,76.6,1874000.0,80.9,1241000.0,84.0,1456000.0,87.6,106000.0,79.1,23252000.0
6,79.1,147000.0,74.2,99000.0,79.9,80000.0,81.6,85000.0,82.8,54000.0,...,74.3,1797000.0,82.0,1258000.0,80.0,1393000.0,85.8,104000.0,76.2,22442000.0
7,77.8,128000.0,83.4,118000.0,71.9,68000.0,85.3,88000.0,74.8,55000.0,...,74.7,1819000.0,79.0,1226000.0,83.3,1474000.0,84.2,103000.0,76.0,22580000.0
8,75.6,125000.0,84.3,117000.0,69.4,73000.0,80.7,76000.0,82.6,60000.0,...,75.0,1831000.0,83.6,1309000.0,82.8,1483000.0,85.3,106000.0,77.2,22912000.0
9,73.8,120000.0,82.9,110000.0,75.6,76000.0,78.3,86000.0,83.0,55000.0,...,74.7,1822000.0,84.8,1334000.0,79.7,1445000.0,85.0,105000.0,77.6,23039000.0
10,75.0,118000.0,82.7,113000.0,72.0,72000.0,68.7,72000.0,69.7,49000.0,...,73.9,1792000.0,83.3,1295000.0,80.2,1441000.0,86.4,105000.0,77.3,22907000.0
11,78.0,126000.0,81.9,114000.0,81.9,84000.0,83.6,90000.0,79.4,55000.0,...,74.3,1795000.0,83.6,1322000.0,83.1,1515000.0,87.4,103000.0,77.6,22964000.0
12,79.3,129000.0,78.4,109000.0,80.8,84000.0,71.6,74000.0,80.2,57000.0,...,74.1,1759000.0,83.4,1311000.0,83.0,1528000.0,77.1,92000.0,77.2,22553000.0

In [ ]:
# Function to reshape the DataFrame into a 8x2 DataFrame
def reshape_dataframe(df):
    # Create an empty list to hold the new rows
    reshaped_rows = []

    # Iterate over every two columns at a time
    for i in range(0, len(df.columns), 2):
        # Take the next two columns
        cols_to_add = df.iloc[:, i:i+2]

        # Append each row of these columns to the reshaped rows list
        reshaped_rows.extend(cols_to_add.values.tolist())

    # Create a new DataFrame from the reshaped rows
    reshaped_df = pd.DataFrame(reshaped_rows)

    return reshaped_df

In [ ]:
increased_risk = reshape_dataframe(increased_risk)
obese = reshape_dataframe(obese)


increased_risk.columns = ['Percentage of Increased Risk Population (23.0-27.49 BMI)', 'Total Increased Risk Population (23.0-27.49 BMI)']
obese.columns = ['Percentage of Obese Population (BMI 27.5 or Higher)', 'Total Obese Population (BMI 27.5 or Higher)']

In [ ]:
obese

,Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher)
0,42.9,73000.0
1,37.3,64000.0
2,39.9,68000.0
3,46.8,82000.0
4,45.6,80000.0
...,...,...
580,42.0,12457000.0
581,42.3,12550000.0
582,42.3,12529000.0
583,42.4,12548000.0
584,42.8,12514000.0

In [ ]:
ob_ir = reshape_dataframe(ob_ir)
ob_ir.columns = ['Percentage of Obese Population (23.0 BMI or Higher)', 'Total Obese Population (23.0 BMI or Higher)']
ob_ir

,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher)
0,78.5,134000.0
1,73.8,126000.0
2,72.3,123000.0
3,84.7,148000.0
4,84.1,148000.0
...,...,...
580,77.2,22912000.0
581,77.6,23039000.0
582,77.3,22907000.0
583,77.6,22964000.0
584,77.2,22553000.0

In [ ]:
df = pd.concat([df, ob_ir], axis=1)
obese_pop_csv = df
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher)
0,Butte,2011,78.5,134000.0
1,Butte,2012,73.8,126000.0
2,Butte,2013,72.3,123000.0
3,Butte,2014,84.7,148000.0
4,Butte,2015,84.1,148000.0
...,...,...,...,...
580,All,2019,77.2,22912000.0
581,All,2020,77.6,23039000.0
582,All,2021,77.3,22907000.0
583,All,2022,77.6,22964000.0
584,All,2023,77.2,22553000.0

In [ ]:
df = pd.concat([df, increased_risk], axis=1)
df = pd.concat([df, obese], axis=1)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher)
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0
...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0

In [ ]:
obese_pop_csv.to_csv('obese_pop_csv.csv')

In [ ]:
race_ethnicity = pd.read_csv('CHIS_race_ethnicity.csv')

race_ethnicity

,Race or Ethnicity,Year,%,Population,%.1,Population.1,%.2,Population.2,%.3,Population.3,...,%.40,Population.40,%.41,Population.41,%.42,Population.42,%.43,Population.43,%.44,Population.44
0,Latino,2011),14.7%,"32,000",9.2%,"16,000",9.8%,"13,000",10.1%,"14,000",...,29.9%,"902,000",47.3%,"949,000",42.3%,"919,000",79.0%,"128,000",37.5%,"13,725,000"
1,Latino,2012),15.9%,"34,000",11.2%,"20,000",16.1%,"21,000",16.0%,"22,000",...,33.3%,"1,012,000",49.5%,"1,000,000",45.6%,"1,004,000",82.5%,"136,000",38.5%,"14,214,000"
2,Latino,2013),18.9%,"41,000",6.7*,"12,000",10.5%,"14,000",13.1%,"18,000",...,33.6%,"1,030,000",49.7%,"1,009,000",45.9%,"1,019,000",82.5%,"136,000",38.8%,"14,454,000"
3,Latino,2014),15.4%,"34,000",10.0%,"18,000",9.0*,"12,000",11.9%,"16,000",...,33.2%,"1,030,000",50.8%,"1,039,000",46.7%,"1,048,000",82.5%,"138,000",38.9%,"14,601,000"
4,Latino,2015),15.2%,"32,000",7.9%,"14,000",10.2%,"13,000",11.0%,"16,000",...,33.3%,"1,049,000",50.1%,"1,017,000",46.6%,"1,072,000",83.9%,"154,000",39.0%,"14,841,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Total,2019),100.0%,"210,000",100.0%,"175,000",100.0%,"129,000",100.0%,"133,000",...,100.0%,"3,238,000",100.0%,"2,129,000",100.0%,"2,378,000",100.0%,"176,000",100.0%,"38,864,000"
100,Total,2020),100.0%,"202,000",100.0%,"175,000",100.0%,"128,000",100.0%,"132,000",...,100.0%,"3,241,000",100.0%,"2,136,000",100.0%,"2,396,000",100.0%,"176,000",100.0%,"38,849,000"
101,Total,2021),100.0%,"199,000",100.0%,"173,000",100.0%,"126,000",100.0%,"130,000",...,100.0%,"3,207,000",100.0%,"2,113,000",100.0%,"2,371,000",100.0%,"173,000",100.0%,"38,431,000"
102,Total,2022),100.0%,"202,000",100.0%,"177,000",100.0%,"129,000",100.0%,"134,000",...,100.0%,"3,171,000",100.0%,"2,134,000",100.0%,"2,385,000",100.0%,"167,000",100.0%,"38,092,000"
103,Total,2023),100.0%,"202,000",100.0%,"176,000",100.0%,"130,000",100.0%,"135,000",...,100.0%,"3,135,000",100.0%,"2,116,000",100.0%,"2,396,000",100.0%,"175,000",100.0%,"38,047,000"

In [ ]:
latino = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'Latino ']
latino = latino.drop(latino.columns[:2], axis = 1)

latino = strip_character_from_dataframe(latino, '%')
latino = strip_character_from_dataframe(latino, '*')
latino = strip_character_from_dataframe(latino, ',')

latino = latino.astype(float)
latino = reshape_dataframe(latino)
latino.columns = ['Percentage of Population that is Latino', 'Total Latino Population']

latino

df = pd.concat([df, latino], axis=1)
df

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0
...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0

In [ ]:
white = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'White non-latino ']

white = white.drop(white.columns[:2], axis = 1)

white = strip_character_from_dataframe(white, '%')
white = strip_character_from_dataframe(white, '*')
white = strip_character_from_dataframe(white, ',')

white = white.astype(float)
white = reshape_dataframe(white)
white.columns = ['Percentage of Population that is White', 'Total White Population']

white

df = pd.concat([df, white], axis=1)
df

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,Percentage of Population that is White,Total White Population
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,77.2,167000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,70.0,151000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,73.0,158000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,74.5,163000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,72.8,156000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,38.3,14902000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,38.2,14846000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,38.0,14618000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,38.1,14522000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,35.3,13434000.0

In [ ]:
black = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'Black or African American non-latino ']

black = black.drop(black.columns[:2], axis = 1)

black = strip_chars(black)


black = black.astype(float)
black = reshape_dataframe(black)
black.columns = ['Percentage of Population that is Black', 'Total Black Population']

black

df = pd.concat([df, black], axis=1)
df

black

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

     Percentage of Population that is Black  Total Black Population
0                                       0.0                     0.0
1                                       2.3                  5000.0
2                                       0.0                     0.0
3                                       1.7                  4000.0
4                                       0.0                     0.0
..                                      ...                     ...
580                                     5.5               2150000.0
581                                     5.5               2153000.0
582                                     5.5               2127000.0
583                                     5.5               2108000.0
584                                     5.4               2058000.0

[585 rows x 2 columns]

In [ ]:
ami = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'American-Indian/Alaska Native non-latino ']

ami = ami.drop(ami.columns[:2], axis = 1)
ami = strip_chars(ami)

ami = ami.astype(float)
ami = reshape_dataframe(ami)
ami.columns = ['Percentage of Population that is American Indian', 'Total American Indian Population']

ami

df = pd.concat([df, ami], axis=1)
df

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,Percentage of Population that is White,Total White Population,Percentage of Population that is Black,Total Black Population,Percentage of Population that is American Indian,Total American Indian Population
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,77.2,167000.0,0.0,0.0,3.1,7000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,70.0,151000.0,2.3,5000.0,0.8,2000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,73.0,158000.0,0.0,0.0,0.6,1000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,74.5,163000.0,1.7,4000.0,1.9,4000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,72.8,156000.0,0.0,0.0,3.4,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,38.3,14902000.0,5.5,2150000.0,0.4,166000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,38.2,14846000.0,5.5,2153000.0,0.4,167000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,38.0,14618000.0,5.5,2127000.0,0.4,166000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,38.1,14522000.0,5.5,2108000.0,0.4,167000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,35.3,13434000.0,5.4,2058000.0,0.4,155000.0

In [ ]:
asian = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'Asian non-latino ']

asian = asian.drop(asian.columns[:2], axis = 1)

asian = strip_chars(asian)

asian = asian.astype(float)
asian = reshape_dataframe(asian)
asian.columns = ['Percentage of Population that is Asian', 'Total American Asian']

asian

df = pd.concat([df, asian], axis=1)
df

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,Percentage of Population that is White,Total White Population,Percentage of Population that is Black,Total Black Population,Percentage of Population that is American Indian,Total American Indian Population,Percentage of Population that is Asian,Total American Asian
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,77.2,167000.0,0.0,0.0,3.1,7000.0,1.3,3000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,70.0,151000.0,2.3,5000.0,0.8,2000.0,7.3,16000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,73.0,158000.0,0.0,0.0,0.6,1000.0,3.6,8000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,74.5,163000.0,1.7,4000.0,1.9,4000.0,6.0,13000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,72.8,156000.0,0.0,0.0,3.4,7000.0,4.3,9000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,38.3,14902000.0,5.5,2150000.0,0.4,166000.0,13.2,5147000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,38.2,14846000.0,5.5,2153000.0,0.4,167000.0,13.2,5135000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,38.0,14618000.0,5.5,2127000.0,0.4,166000.0,13.2,5069000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,38.1,14522000.0,5.5,2108000.0,0.4,167000.0,13.1,4981000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,35.3,13434000.0,5.4,2058000.0,0.4,155000.0,15.6,5930000.0

In [ ]:
api = race_ethnicity[race_ethnicity['Race or Ethnicity'] == 'Native Hawaiian/Pacific Islander non-latino ']

api = api.drop(api.columns[:2], axis = 1)
api = strip_chars(api)

api = api.astype(float)
api = reshape_dataframe(api)
api.columns = ['Percentage of Population that is Pacific Islander', 'Total American Pacific Islander Population']

api
df = pd.concat([df, api], axis=1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
income = pd.read_csv('Income Brackets.csv')
low = income[income['Unnamed: 0'] == '0-99% FPL ']
low_mid = income[income['Unnamed: 0'] == '100-199% FPL ']
upper_mid = income[income['Unnamed: 0'] == '200-299% FPL ']
upper = income[income['Unnamed: 0'] == '300% FPL and above ']

In [ ]:
def basics(df):
  df = df.drop(df.columns[:2], axis = 1)
  df = strip_chars(df)
  df = df.astype(float)
  df = reshape_dataframe(df)
  return df

In [ ]:
low = basics(low)
low.columns = ['% in 0-99% API Bracket', 'Total Population in 0-99% API Bracket']

df = pd.concat([df, low], axis = 1)
df

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,Percentage of Population that is Black,Total Black Population,Percentage of Population that is American Indian,Total American Indian Population,Percentage of Population that is Asian,Total American Asian,Percentage of Population that is Pacific Islander,Total American Pacific Islander Population,% in 0-99% API Bracket,Total Population in 0-99% API Bracket
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,0.0,0.0,3.1,7000.0,1.3,3000.0,0.0,0.0,19.6,42000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,2.3,5000.0,0.8,2000.0,7.3,16000.0,0.0,0.0,26.0,56000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,0.0,0.0,0.6,1000.0,3.6,8000.0,0.0,0.0,20.8,45000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,1.7,4000.0,1.9,4000.0,6.0,13000.0,0.0,0.0,14.2,31000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,0.0,0.0,3.4,7000.0,4.3,9000.0,0.0,0.0,16.8,36000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,5.5,2150000.0,0.4,166000.0,13.2,5147000.0,0.4,139000.0,14.7,5721000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,5.5,2153000.0,0.4,167000.0,13.2,5135000.0,0.4,139000.0,13.7,5313000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,5.5,2127000.0,0.4,166000.0,13.2,5069000.0,0.4,138000.0,13.4,5146000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,5.5,2108000.0,0.4,167000.0,13.1,4981000.0,0.4,137000.0,14.7,5599000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,5.4,2058000.0,0.4,155000.0,15.6,5930000.0,0.4,136000.0,14.7,5597000.0

In [ ]:
low_mid = basics(low_mid)
low_mid.columns = ['% in 100-199% API Bracket', 'Total Population in 100-199% Bracket']

df = pd.concat([df, low_mid], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
upper_mid = basics(upper_mid)
upper_mid.columns = ['% in 200-299% API Bracket', 'Total Population in 200-299% Bracket']

df = pd.concat([df, upper_mid], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
upper = basics(upper)
upper.columns = ['% in 300% and Higher API Bracket', 'Total Population in 300% and Higher Bracket']

df = pd.concat([df, upper], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,Percentage of Population that is Pacific Islander,Total American Pacific Islander Population,% in 0-99% API Bracket,Total Population in 0-99% API Bracket,% in 100-199% API Bracket,Total Population in 100-199% Bracket,% in 200-299% API Bracket,Total Population in 200-299% Bracket,% in 300% and Higher API Bracket,Total Population in 300% and Higher Bracket
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,0.0,0.0,19.6,42000.0,24.5,53000.0,18.4,40000.0,37.5,81000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,0.0,0.0,26.0,56000.0,23.3,50000.0,21.4,46000.0,29.2,63000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,0.0,0.0,20.8,45000.0,16.9,37000.0,9.5,21000.0,52.8,114000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,0.0,0.0,14.2,31000.0,22.1,48000.0,14.4,31000.0,49.2,108000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,0.0,0.0,16.8,36000.0,22.8,49000.0,23.5,50000.0,36.9,79000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,0.4,139000.0,14.7,5721000.0,17.3,6737000.0,13.4,5222000.0,54.5,21184000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,0.4,139000.0,13.7,5313000.0,15.4,5977000.0,13.0,5045000.0,58.0,22514000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,0.4,138000.0,13.4,5146000.0,16.6,6397000.0,12.0,4616000.0,58.0,22273000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,0.4,137000.0,14.7,5599000.0,15.2,5795000.0,11.8,4484000.0,58.3,22214000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,0.4,136000.0,14.7,5597000.0,15.2,5766000.0,11.2,4280000.0,58.9,22404000.0

In [ ]:
edu = pd.read_csv('education_level.csv')
gs = edu[edu['Unnamed: 0'] == 'Grades 1-8 ']
shs = edu[edu['Unnamed: 0'] == 'Grades 9-11 ']
hs = edu[edu['Unnamed: 0'] == 'Grade 12  ']
sc = edu[edu['Unnamed: 0'] == 'Some college ']
vs = edu[edu['Unnamed: 0'] == 'Vocational school ']
aa = edu[edu['Unnamed: 0'] == 'AA/AS degree ']
ba = edu[edu['Unnamed: 0'] == 'BA/BS degree ']
sgs = edu[edu['Unnamed: 0'] == 'Some graduate school ']
ma = edu[edu['Unnamed: 0'] == 'MA/MS degree ']
phd = edu[edu['Unnamed: 0'] == 'PhD or equivalent ']
ne = edu[edu['Unnamed: 0'] == 'No formal education ']

In [ ]:
gs = basics(gs)
gs.columns = ['% of Population with Grades 1-8 Completed', 'Total Population with Grades 1-8 Completed']

df = pd.concat([df, gs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
shs = basics(shs)
shs.columns = ['% of Population with Some High School Completed', 'Total Population with Some High School Completed']

df = pd.concat([df, shs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
hs = basics(hs)
hs.columns = ['% of Population with High School Completed', 'Total Population with High School Completed']

df = pd.concat([df, hs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
sc = basics(sc)
sc.columns = ['% of Population with Some College Completed', 'Total Population with Some College Completed']

df = pd.concat([df, sc], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
vs = basics(vs)
vs.columns = ['% of Population with Vocational School Completed', 'Total Population with Vocational School Completed']

df = pd.concat([df, vs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
aa = basics(aa)
aa.columns = ['% of Population with an AA/AS degree', 'Total Population with an AA/AS degree']

df = pd.concat([df, aa], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ba = basics(ba)
ba.columns = ['% of Population with a BA/BS degree', 'Total Population with a BA/BS degree']

df = pd.concat([df, ba], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
sgs = basics(sgs)
sgs.columns = ['% of Population with Some Grad School Completed', 'Total Population with Some Grad School Completed']

df = pd.concat([df, sgs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ma = basics(ma)
ma.columns = ['% of Population with an MA/MS Degree', 'Total Population with an MA/MS Degree']

df = pd.concat([df, hs], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
phd = basics(phd)
phd.columns = ['% of Population with PhD', 'Total Population with PhD']

df = pd.concat([df, phd], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ne = basics(ne)
ne.columns = ['% of Population with No Formal Education', 'Total Population with No Formal Education']

df = pd.concat([df, ne], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,% of Population with a BA/BS degree,Total Population with a BA/BS degree,% of Population with Some Grad School Completed,Total Population with Some Grad School Completed,% of Population with High School Completed,Total Population with High School Completed,% of Population with PhD,Total Population with PhD,% of Population with No Formal Education,Total Population with No Formal Education
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,20.7,45000.0,0.8,2000.0,21.5,47000.0,3.0,6000.0,0.0,0.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,16.3,35000.0,1.4,3000.0,17.6,38000.0,3.3,7000.0,0.0,0.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,23.8,52000.0,0.4,1000.0,25.3,55000.0,2.9,6000.0,0.0,0.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,20.2,44000.0,0.0,0.0,26.2,57000.0,1.2,3000.0,0.0,0.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,25.0,44000.0,0.0,0.0,28.6,50000.0,1.7,3000.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,21.6,6397000.0,2.1,620000.0,22.3,6617000.0,5.0,1470000.0,0.8,251000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,22.8,6760000.0,2.1,620000.0,21.8,6477000.0,4.7,1385000.0,1.2,363000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,22.9,6800000.0,1.9,576000.0,22.0,6510000.0,5.2,1531000.0,1.1,319000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,23.1,6815000.0,2.1,608000.0,22.2,6567000.0,5.4,1589000.0,1.2,355000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,23.5,6871000.0,2.0,586000.0,22.5,6583000.0,5.6,1634000.0,0.9,269000.0

In [ ]:
employ = pd.read_csv('employment_levels.csv')
full = employ[employ['Unnamed: 0'] == 'Full-time employed  ']
part = employ[employ['Unnamed: 0'] == 'Part-time employed  ']
em_naw = employ[employ['Unnamed: 0'] == 'Employed, not at work last week ']
ue_lfw = employ[employ['Unnamed: 0'] == 'Unemployed and looking for work ']
ue_nlfw = employ[employ['Unnamed: 0'] == 'Unemployed and not looking for work ']

In [ ]:
full = basics(full)
full.columns = ['% of Population Full Time Employed', 'Total Population Full Time Employed']

df = pd.concat([df, full], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
part = basics(part)
part.columns = ['% of Population Part Time Employed', 'Total Population Employed']

df = pd.concat([df, part], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
em_naw = basics(em_naw)
em_naw.columns = ['% of Population Employed, not at Work in Last Week', 'Total Population Employed, not at Work in Last Week']

df = pd.concat([df, em_naw], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ue_lfw = basics(ue_lfw)
ue_lfw.columns = ['% of Population Unemployed, Looking for Work', 'Total Population Unemployed, Looking for Work']

df = pd.concat([df, ue_lfw], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ue_nlfw = basics(ue_nlfw)
ue_nlfw.columns = ['% of Population Unemployed, not Looking for Work', 'Total Population Unemployed, not Looking for Work']

df = pd.concat([df, ue_nlfw], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
ru = pd.read_csv('rural_urban.csv')
urban = ru[ru['Unnamed: 0'] == 'Urban']
rural = ru[ru['Unnamed: 0'] == 'Rural']

In [ ]:
urban = basics(urban)
urban.columns = ['% of Population living in Urban Areas', 'Total Population living In Urban Areas']

df = pd.concat([df, urban], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
rural = basics(rural)
rural.columns = ['% of Population living in Rural Areas', 'Total Population living In Rural Areas']

df = pd.concat([df, rural], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,"% of Population Employed, not at Work in Last Week","Total Population Employed, not at Work in Last Week","% of Population Unemployed, Looking for Work","Total Population Unemployed, Looking for Work","% of Population Unemployed, not Looking for Work","Total Population Unemployed, not Looking for Work",% of Population living in Urban Areas,Total Population living In Urban Areas,% of Population living in Rural Areas,Total Population living In Rural Areas
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,0.0,0.0,9.4,16000.0,37.4,64000.0,49.8,108000.0,50.2,109000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,0.0,0.0,11.2,19000.0,38.3,65000.0,39.6,85000.0,60.4,130000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,0.0,0.0,6.1,10000.0,34.1,58000.0,65.7,142000.0,34.3,74000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,0.0,0.0,9.4,16000.0,34.2,60000.0,46.5,102000.0,53.5,117000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,0.0,0.0,4.8,9000.0,41.3,73000.0,50.5,108000.0,49.5,106000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,0.9,278000.0,5.8,1721000.0,30.3,8999000.0,90.5,35176000.0,9.5,3688000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,1.3,372000.0,6.1,1820000.0,29.4,8738000.0,88.6,34433000.0,11.4,4416000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,1.0,303000.0,7.8,2308000.0,30.5,9037000.0,90.9,34945000.0,9.1,3485000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,1.2,349000.0,6.4,1889000.0,30.6,9060000.0,90.2,34364000.0,9.8,3727000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,1.1,314000.0,6.5,1905000.0,31.8,9293000.0,90.0,34241000.0,10.0,3806000.0

In [ ]:
insure = pd.read_csv('insurance (1) (1).csv')
uninsured = insure[insure['Unnamed: 0'] == 'Uninsured ']
mcare_mcaid = insure[insure['Unnamed: 0'] == 'Medicare & Medicaid ']
mcare_others = insure[insure['Unnamed: 0'] == 'Medicare & Others ']
medicare = insure[insure['Unnamed: 0'] == 'Medicare only ']
medicaid = insure[insure['Unnamed: 0'] == 'Medicaid ']
chip = insure[insure['Unnamed: 0'] == 'Healthy Families/CHIP ']
emp_based = insure[insure['Unnamed: 0'] == 'Employment-based ']
private = insure[insure['Unnamed: 0'] == 'Privately purchased ']
other = insure[insure['Unnamed: 0'] == 'Other public ']

In [ ]:
medicaid

,Unnamed: 0,Unnamed: 1,%,Population,%.1,Population.1,%.2,Population.2,%.3,Population.3,...,%.40,Population.40,%.41,Population.41,%.42,Population.42,%.43,Population.43,%.44,Population.44
52,Medicaid,2011),20.20%,"44,000",15.20%,"27,000",16.90%,"22,000",19.30%,"27,000",...,12.40%,"375,000",22.90%,"460,000",19.50%,"423,000",23.60%,"38,000",16.30%,"5,988,000"
53,Medicaid,2012),16.70%,"36,000",12.00%,"21,000",28.10%,"36,000",31.60%,"43,000",...,11.30%,"343,000",17.80%,"359,000",19.10%,"420,000",34.00%,"56,000",16.60%,"6,148,000"
54,Medicaid,2013),18.40%,"40,000",26.40%,"46,000",17.60%,"23,000",14.60%,"20,000",...,11.70%,"358,000",26.20%,"532,000",15.50%,"344,000",29.00%,"48,000",16.80%,"6,271,000"
55,Medicaid,2014),27.50%,"60,000",21.80%,"38,000",15.50%,"20,000",19.90%,"27,000",...,18.20%,"564,000",29.40%,"601,000",26.20%,"588,000",39.20%,"66,000",22.50%,"8,455,000"
56,Medicaid,2015),26.70%,"57,000",27.00%,"48,000",31.00%,"40,000",25.60%,"36,000",...,25.40%,"803,000",32.20%,"652,000",29.00%,"667,000",39.80%,"73,000",27.10%,"10,338,000"
57,Medicaid,2016),27.70%,"65,000",27.30%,"45,000",32.40%,"40,000",16.1*,"27,000",...,24.30%,"773,000",32.60%,"701,000",30.80%,"741,000",41.60%,"72,000",28.70%,"11,014,000"
58,Medicaid,2017),34.1*,"75,000",10.1*,"18,000",19.20%,"25,000",29.80%,"40,000",...,20.40%,"656,000",35.00%,"740,000",28.80%,"674,000",42.60%,"75,000",25.00%,"9,669,000"
59,Medicaid,2018),29.1*,"65,000",30.7*,"54,000",33.70%,"44,000",20.5*,"28,000",...,24.30%,"785,000",28.40%,"604,000",27.30%,"647,000",45.50%,"80,000",25.40%,"9,865,000"
60,Medicaid,2019),22.80%,"48,000",31.20%,"55,000",29.30%,"38,000",21.00%,"28,000",...,17.50%,"566,000",30.90%,"658,000",26.30%,"626,000",41.30%,"73,000",21.00%,"8,177,000"
61,Medicaid,2020),15.80%,"32,000",20.20%,"35,000",26.20%,"34,000",12.30%,"16,000",...,15.40%,"498,000",25.10%,"535,000",23.50%,"564,000",41.20%,"72,000",21.10%,"8,198,000"
62,Medicaid,2021),21.10%,"42,000",23.40%,"40,000",25.80%,"33,000",16.80%,"22,000",...,16.20%,"519,000",28.00%,"592,000",28.80%,"682,000",49.10%,"85,000",22.30%,"8,556,000"
63,Medicaid,2022),21.70%,"44,000",16.90%,"30,000",27.30%,"35,000",36.00%,"48,000",...,15.50%,"491,000",27.80%,"592,000",29.20%,"696,000",34.20%,"57,000",22.30%,"8,496,000"
64,Medicaid,2023),34.00%,"69,000",27.50%,"48,000",25.90%,"34,000",32.60%,"44,000",...,17.50%,"549,000",28.60%,"606,000",27.70%,"664,000",43.70%,"76,000",24.00%,"9,135,000"

In [ ]:
emp_based

,Unnamed: 0,Unnamed: 1,%,Population,%.1,Population.1,%.2,Population.2,%.3,Population.3,...,%.40,Population.40,%.41,Population.41,%.42,Population.42,%.43,Population.43,%.44,Population.44
78,Employment-based,2011),38.50%,"83,000",41.90%,"73,000",36.10%,"47,000",39.30%,"55,000",...,53.40%,"1,611,000",42.00%,"843,000",42.80%,"930,000",37.50%,"61,000",47.20%,"17,291,000"
79,Employment-based,2012),40.00%,"86,000",47.40%,"83,000",33.60%,"44,000",32.80%,"45,000",...,50.40%,"1,532,000",43.60%,"880,000",45.30%,"996,000",35.20%,"58,000",46.50%,"17,163,000"
80,Employment-based,2013),44.20%,"96,000",44.30%,"78,000",32.80%,"43,000",45.40%,"63,000",...,50.00%,"1,534,000",41.60%,"843,000",45.70%,"1,013,000",40.10%,"66,000",47.70%,"17,777,000"
81,Employment-based,2014),44.20%,"97,000",35.80%,"63,000",35.70%,"46,000",40.10%,"55,000",...,46.70%,"1,448,000",43.00%,"880,000",34.60%,"777,000",31.90%,"53,000",44.80%,"16,830,000"
82,Employment-based,2015),44.10%,"95,000",27.60%,"49,000",33.60%,"43,000",31.00%,"44,000",...,42.80%,"1,351,000",34.90%,"707,000",37.50%,"862,000",32.50%,"60,000",42.90%,"16,343,000"
83,Employment-based,2016),48.70%,"115,000",28.90%,"48,000",24.50%,"30,000",48.1*,"81,000",...,47.20%,"1,503,000",38.70%,"833,000",41.60%,"999,000",25.70%,"44,000",42.10%,"16,150,000"
84,Employment-based,2017),27.4*,"61,000",50.80%,"89,000",43.70%,"57,000",29.10%,"39,000",...,49.20%,"1,579,000",37.70%,"797,000",35.60%,"832,000",28.60%,"50,000",44.40%,"17,186,000"
85,Employment-based,2018),45.30%,"101,000",36.90%,"65,000",35.40%,"46,000",37.50%,"51,000",...,45.20%,"1,461,000",44.30%,"944,000",39.10%,"927,000",26.10%,"46,000",44.80%,"17,423,000"
86,Employment-based,2019),46.40%,"97,000",35.00%,"61,000",32.20%,"42,000",46.30%,"61,000",...,55.20%,"1,788,000",43.30%,"921,000",43.80%,"1,043,000",37.00%,"65,000",50.40%,"19,574,000"
87,Employment-based,2020),50.80%,"102,000",41.60%,"73,000",43.10%,"55,000",35.40%,"47,000",...,57.10%,"1,852,000",52.20%,"1,115,000",44.80%,"1,074,000",29.50%,"52,000",51.40%,"19,975,000"
88,Employment-based,2021),43.30%,"86,000",46.30%,"80,000",43.30%,"55,000",34.70%,"45,000",...,55.30%,"1,773,000",40.70%,"859,000",42.10%,"997,000",30.30%,"52,000",49.30%,"18,933,000"
89,Employment-based,2022),48.00%,"97,000",48.10%,"85,000",33.90%,"44,000",26.30%,"35,000",...,55.80%,"1,769,000",47.90%,"1,021,000",39.10%,"931,000",42.10%,"70,000",49.30%,"18,796,000"
90,Employment-based,2023),36.90%,"75,000",37.80%,"67,000",36.50%,"47,000",38.00%,"51,000",...,57.50%,"1,802,000",45.10%,"954,000",45.40%,"1,087,000",31.90%,"56,000",49.30%,"18,772,000"

In [ ]:
private

,Unnamed: 0,Unnamed: 1,%,Population,%.1,Population.1,%.2,Population.2,%.3,Population.3,...,%.40,Population.40,%.41,Population.41,%.42,Population.42,%.43,Population.43,%.44,Population.44
91,Privately purchased,2011),4.00%,"9,000",2.5*,"4,000",7.30%,"10,000",2.2*,"3,000",...,5.50%,"165,000",3.70%,"75,000",4.30%,"94,000",2.6*,"4,000",5.60%,"2,054,000"
92,Privately purchased,2012),2.0*,"4,000",2.6*,"5,000",9.3*,"12,000",2.5*,"3,000",...,5.50%,"167,000",4.0*,"80,000",4.30%,"95,000",1.4*,"2,000",5.20%,"1,914,000"
93,Privately purchased,2013),2.6*,"6,000",3.6*,"6,000",9.10%,"12,000",2.7*,"4,000",...,5.80%,"178,000",4.0*,"81,000",6.2*,"138,000",0.6*,"1,000",5.40%,"1,996,000"
94,Privately purchased,2014),3.4*,"8,000",4.9*,"9,000",7.6*,"10,000",12.2*,"17,000",...,7.10%,"221,000",3.0*,"61,000",3.9*,"87,000",10.0*,"17,000",6.40%,"2,409,000"
95,Privately purchased,2015),6.2*,"13,000",8.9*,"16,000",4.5*,"6,000",5.0*,"7,000",...,6.60%,"207,000",5.50%,"111,000",6.20%,"142,000",3.5*,"6,000",6.10%,"2,317,000"
96,Privately purchased,2016),4.9*,"11,000",7.4*,"12,000",6.0*,"7,000",9.7*,"16,000",...,6.60%,"209,000",3.9*,"85,000",6.10%,"148,000",2.2*,"4,000",6.00%,"2,314,000"
97,Privately purchased,2017),7.2*,"16,000",4.8*,"8,000",5.5*,"7,000",3.2*,"4,000",...,7.40%,"236,000",4.5*,"95,000",7.4*,"173,000",1.6*,"3,000",6.50%,"2,510,000"
98,Privately purchased,2018),4.1*,"9,000",7.0*,"12,000",10.8*,"14,000",4.3*,"6,000",...,6.00%,"194,000",5.60%,"119,000",3.7*,"87,000",3.5*,"6,000",5.80%,"2,266,000"
99,Privately purchased,2019),7.00%,"15,000",2.40%,"4,000",6.00%,"8,000",2.90%,"4,000",...,4.30%,"140,000",4.10%,"86,000",4.30%,"101,000",5.30%,"9,000",4.80%,"1,852,000"
100,Privately purchased,2020),9.00%,"18,000",4.70%,"8,000",5.30%,"7,000",3.60%,"5,000",...,4.50%,"146,000",3.10%,"66,000",5.20%,"125,000",7.90%,"14,000",4.70%,"1,834,000"
101,Privately purchased,2021),9.70%,"19,000",4.70%,"8,000",3.30%,"4,000",7.10%,"9,000",...,4.70%,"150,000",3.40%,"72,000",4.30%,"102,000",4.20%,"7,000",5.00%,"1,904,000"
102,Privately purchased,2022),7.30%,"15,000",6.80%,"12,000",5.10%,"7,000",6.6*,"9,000",...,4.50%,"141,000",3.50%,"74,000",4.60%,"110,000",2.1*,"4,000",4.30%,"1,651,000"
103,Privately purchased,2023),3.1*,"6,000",1.80%,"3,000",6.10%,"8,000",9.20%,"12,000",...,4.00%,"124,000",4.40%,"93,000",4.00%,"97,000",3.8*,"7,000",4.10%,"1,560,000"

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,"% of Population Employed, not at Work in Last Week","Total Population Employed, not at Work in Last Week","% of Population Unemployed, Looking for Work","Total Population Unemployed, Looking for Work","% of Population Unemployed, not Looking for Work","Total Population Unemployed, not Looking for Work",% of Population living in Urban Areas,Total Population living In Urban Areas,% of Population living in Rural Areas,Total Population living In Rural Areas
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,0.0,0.0,9.4,16000.0,37.4,64000.0,49.8,108000.0,50.2,109000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,0.0,0.0,11.2,19000.0,38.3,65000.0,39.6,85000.0,60.4,130000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,0.0,0.0,6.1,10000.0,34.1,58000.0,65.7,142000.0,34.3,74000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,0.0,0.0,9.4,16000.0,34.2,60000.0,46.5,102000.0,53.5,117000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,0.0,0.0,4.8,9000.0,41.3,73000.0,50.5,108000.0,49.5,106000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,0.9,278000.0,5.8,1721000.0,30.3,8999000.0,90.5,35176000.0,9.5,3688000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,1.3,372000.0,6.1,1820000.0,29.4,8738000.0,88.6,34433000.0,11.4,4416000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,1.0,303000.0,7.8,2308000.0,30.5,9037000.0,90.9,34945000.0,9.1,3485000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,1.2,349000.0,6.4,1889000.0,30.6,9060000.0,90.2,34364000.0,9.8,3727000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,1.1,314000.0,6.5,1905000.0,31.8,9293000.0,90.0,34241000.0,10.0,3806000.0

In [ ]:
uninsured = basics(uninsured)
uninsured.columns = ['% Population that is Uninsured', 'Total Population that is Uninsured']
uninsured
df = pd.concat([df, uninsured], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
mcare_mcaid = basics(mcare_mcaid)
mcare_mcaid.columns = ['% of Population insured through Medicare & Medicaid', 'Total Population insured through Medicare & Medicaid']
mcare_mcaid
df = pd.concat([df, mcare_mcaid], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,"% of Population Unemployed, not Looking for Work","Total Population Unemployed, not Looking for Work",% of Population living in Urban Areas,Total Population living In Urban Areas,% of Population living in Rural Areas,Total Population living In Rural Areas,% Population that is Uninsured,Total Population that is Uninsured,% of Population insured through Medicare & Medicaid,Total Population insured through Medicare & Medicaid
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,37.4,64000.0,49.8,108000.0,50.2,109000.0,17.8,38000.0,3.4,7000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,38.3,65000.0,39.6,85000.0,60.4,130000.0,17.3,37000.0,5.1,11000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,34.1,58000.0,65.7,142000.0,34.3,74000.0,14.5,31000.0,3.4,7000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,34.2,60000.0,46.5,102000.0,53.5,117000.0,8.9,19000.0,2.3,5000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,41.3,73000.0,50.5,108000.0,49.5,106000.0,3.8,8000.0,5.9,13000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,30.3,8999000.0,90.5,35176000.0,9.5,3688000.0,7.2,2791000.0,3.2,1246000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,29.4,8738000.0,88.6,34433000.0,11.4,4416000.0,6.0,2317000.0,3.0,1170000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,30.5,9037000.0,90.9,34945000.0,9.1,3485000.0,6.3,2422000.0,3.6,1381000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,30.6,9060000.0,90.2,34364000.0,9.8,3727000.0,5.2,1966000.0,3.8,1449000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,31.8,9293000.0,90.0,34241000.0,10.0,3806000.0,4.5,1704000.0,3.9,1468000.0

In [ ]:
mcare_others = basics(mcare_others)
mcare_others.columns = ['% of Population insured through Medicare & others', 'Total Population insured through Medicare & others']
mcare_others
df = pd.concat([df, mcare_others], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,% of Population living in Urban Areas,Total Population living In Urban Areas,% of Population living in Rural Areas,Total Population living In Rural Areas,% Population that is Uninsured,Total Population that is Uninsured,% of Population insured through Medicare & Medicaid,Total Population insured through Medicare & Medicaid,% of Population insured through Medicare & others,Total Population insured through Medicare & others
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,49.8,108000.0,50.2,109000.0,17.8,38000.0,3.4,7000.0,10.2,22000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,39.6,85000.0,60.4,130000.0,17.3,37000.0,5.1,11000.0,12.1,26000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,65.7,142000.0,34.3,74000.0,14.5,31000.0,3.4,7000.0,13.0,28000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,46.5,102000.0,53.5,117000.0,8.9,19000.0,2.3,5000.0,13.2,29000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,50.5,108000.0,49.5,106000.0,3.8,8000.0,5.9,13000.0,10.0,21000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,90.5,35176000.0,9.5,3688000.0,7.2,2791000.0,3.2,1246000.0,10.9,4245000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,88.6,34433000.0,11.4,4416000.0,6.0,2317000.0,3.0,1170000.0,11.2,4368000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,90.9,34945000.0,9.1,3485000.0,6.3,2422000.0,3.6,1381000.0,11.4,4382000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,90.2,34364000.0,9.8,3727000.0,5.2,1966000.0,3.8,1449000.0,12.4,4724000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,90.0,34241000.0,10.0,3806000.0,4.5,1704000.0,3.9,1468000.0,12.3,4664000.0

In [ ]:
medicare = basics(medicare)
medicare.columns = ['% of Population insured through Medicare only', 'Total Population insured through Medicare only']
medicare
df = pd.concat([df, medicare], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,% of Population living in Rural Areas,Total Population living In Rural Areas,% Population that is Uninsured,Total Population that is Uninsured,% of Population insured through Medicare & Medicaid,Total Population insured through Medicare & Medicaid,% of Population insured through Medicare & others,Total Population insured through Medicare & others,% of Population insured through Medicare only,Total Population insured through Medicare only
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,50.2,109000.0,17.8,38000.0,3.4,7000.0,10.2,22000.0,3.2,7000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,60.4,130000.0,17.3,37000.0,5.1,11000.0,12.1,26000.0,3.2,7000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,34.3,74000.0,14.5,31000.0,3.4,7000.0,13.0,28000.0,3.4,7000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,53.5,117000.0,8.9,19000.0,2.3,5000.0,13.2,29000.0,0.4,1000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,49.5,106000.0,3.8,8000.0,5.9,13000.0,10.0,21000.0,2.5,5000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,9.5,3688000.0,7.2,2791000.0,3.2,1246000.0,10.9,4245000.0,1.6,633000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,11.4,4416000.0,6.0,2317000.0,3.0,1170000.0,11.2,4368000.0,1.5,564000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,9.1,3485000.0,6.3,2422000.0,3.6,1381000.0,11.4,4382000.0,1.4,522000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,9.8,3727000.0,5.2,1966000.0,3.8,1449000.0,12.4,4724000.0,1.4,550000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,10.0,3806000.0,4.5,1704000.0,3.9,1468000.0,12.3,4664000.0,1.1,435000.0

In [ ]:
medicaid = basics(medicaid)
medicaid.columns = ['% of Population insured through Medicaid', 'Total Population insured through Medicaid']

df = pd.concat([df, medicaid], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,% Population that is Uninsured,Total Population that is Uninsured,% of Population insured through Medicare & Medicaid,Total Population insured through Medicare & Medicaid,% of Population insured through Medicare & others,Total Population insured through Medicare & others,% of Population insured through Medicare only,Total Population insured through Medicare only,% of Population insured through Medicaid,Total Population insured through Medicaid
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,17.8,38000.0,3.4,7000.0,10.2,22000.0,3.2,7000.0,20.2,44000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,17.3,37000.0,5.1,11000.0,12.1,26000.0,3.2,7000.0,16.7,36000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,14.5,31000.0,3.4,7000.0,13.0,28000.0,3.4,7000.0,18.4,40000.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,8.9,19000.0,2.3,5000.0,13.2,29000.0,0.4,1000.0,27.5,60000.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,3.8,8000.0,5.9,13000.0,10.0,21000.0,2.5,5000.0,26.7,57000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,7.2,2791000.0,3.2,1246000.0,10.9,4245000.0,1.6,633000.0,21.0,8177000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,6.0,2317000.0,3.0,1170000.0,11.2,4368000.0,1.5,564000.0,21.1,8198000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,6.3,2422000.0,3.6,1381000.0,11.4,4382000.0,1.4,522000.0,22.3,8556000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,5.2,1966000.0,3.8,1449000.0,12.4,4724000.0,1.4,550000.0,22.3,8496000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,4.5,1704000.0,3.9,1468000.0,12.3,4664000.0,1.1,435000.0,24.0,9135000.0

In [ ]:
chip = basics(chip)
chip.columns = ['% of Population insured through Healthy Families/ CHIP', 'Total Population insured through Healthy Families/ CHIP']
chip
df = pd.concat([df, chip], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('-', 0)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
chip

,% of Population insured through Healthy Families/ CHIP,Total Population insured through Healthy Families/ CHIP
0,0.0,0.0
1,1.3,3000.0
2,0.0,0.0
3,0.0,0.0
4,0.0,0.0
...,...,...
580,0.0,0.0
581,0.0,0.0
582,0.0,0.0
583,0.0,0.0
584,0.0,0.0

In [ ]:
emp_based = basics(emp_based)
emp_based.columns = ['% of Population insured through Employment', 'Total Population insured through Employment']
emp_based
df = pd.concat([df, emp_based], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
emp_based

,% of Population insured through Employment,Total Population insured through Employment
0,38.5,83000.0
1,40.0,86000.0
2,44.2,96000.0
3,44.2,97000.0
4,44.1,95000.0
...,...,...
580,50.4,19574000.0
581,51.4,19975000.0
582,49.3,18933000.0
583,49.3,18796000.0
584,49.3,18772000.0

In [ ]:
private = basics(private)
private.columns = ['% of Population insured Privately', 'Total Population insured Privately']
private
df = pd.concat([df, private], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
private

     % of Population insured Privately  Total Population insured Privately
0                                  4.0                              9000.0
1                                  2.0                              4000.0
2                                  2.6                              6000.0
3                                  3.4                              8000.0
4                                  6.2                             13000.0
..                                 ...                                 ...
580                                4.8                           1852000.0
581                                4.7                           1834000.0
582                                5.0                           1904000.0
583                                4.3                           1651000.0
584                                4.1                           1560000.0

[585 rows x 2 columns]

In [ ]:
other = basics(other)
other.columns = ['% of Population with Other Public Insurance', 'Total Population with Other Public Insurance']
other
df = pd.concat([df, other], axis = 1)

<ipython-input-196-849b272fb6d4>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: x.replace(char_to_strip, '') if isinstance(x, str) else x)
<ipython-input-197-fb349ec027cb>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x.replace('-', '0') if isinstance(x, str) else x)

In [ ]:
other

,% of Population with Other Public Insurance,Total Population with Other Public Insurance
0,2.6,6000.0
1,2.2,5000.0
2,0.0,0.0
3,0.0,0.0
4,0.7,2000.0
...,...,...
580,0.9,344000.0
581,1.1,423000.0
582,0.9,331000.0
583,1.2,459000.0
584,0.8,311000.0

In [ ]:
df.to_csv('obesity.csv')

In [ ]:
df

,County,Year,Percentage of Obese Population (23.0 BMI or Higher),Total Obese Population (23.0 BMI or Higher),Percentage of Increased Risk Population (23.0-27.49 BMI),Total Increased Risk Population (23.0-27.49 BMI),Percentage of Obese Population (BMI 27.5 or Higher),Total Obese Population (BMI 27.5 or Higher),Percentage of Population that is Latino,Total Latino Population,...,% of Population insured through Medicaid,Total Population insured through Medicaid,% of Population insured through Healthy Families/ CHIP,Total Population insured through Healthy Families/ CHIP,% of Population insured through Employment,Total Population insured through Employment,% of Population insured Privately,Total Population insured Privately,% of Population with Other Public Insurance,Total Population with Other Public Insurance
0,Butte,2011,78.5,134000.0,35.6,61000.0,42.9,73000.0,14.7,32000.0,...,20.2,44000.0,0.0,0.0,38.5,83000.0,4.0,9000.0,2.6,6000.0
1,Butte,2012,73.8,126000.0,36.5,62000.0,37.3,64000.0,15.9,34000.0,...,16.7,36000.0,1.3,3000.0,40.0,86000.0,2.0,4000.0,2.2,5000.0
2,Butte,2013,72.3,123000.0,32.4,55000.0,39.9,68000.0,18.9,41000.0,...,18.4,40000.0,0.0,0.0,44.2,96000.0,2.6,6000.0,0.0,0.0
3,Butte,2014,84.7,148000.0,37.9,66000.0,46.8,82000.0,15.4,34000.0,...,27.5,60000.0,0.0,0.0,44.2,97000.0,3.4,8000.0,0.0,0.0
4,Butte,2015,84.1,148000.0,38.5,68000.0,45.6,80000.0,15.2,32000.0,...,26.7,57000.0,0.0,0.0,44.1,95000.0,6.2,13000.0,0.7,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,All,2019,77.2,22912000.0,35.2,10455000.0,42.0,12457000.0,39.4,15304000.0,...,21.0,8177000.0,0.0,0.0,50.4,19574000.0,4.8,1852000.0,0.9,344000.0
581,All,2020,77.6,23039000.0,35.3,10489000.0,42.3,12550000.0,39.5,15341000.0,...,21.1,8198000.0,0.0,0.0,51.4,19975000.0,4.7,1834000.0,1.1,423000.0
582,All,2021,77.3,22907000.0,35.0,10378000.0,42.3,12529000.0,39.7,15239000.0,...,22.3,8556000.0,0.0,0.0,49.3,18933000.0,5.0,1904000.0,0.9,331000.0
583,All,2022,77.6,22964000.0,35.2,10416000.0,42.4,12548000.0,39.6,15103000.0,...,22.3,8496000.0,0.0,0.0,49.3,18796000.0,4.3,1651000.0,1.2,459000.0
584,All,2023,77.2,22553000.0,34.4,10039000.0,42.8,12514000.0,39.9,15185000.0,...,24.0,9135000.0,0.0,0.0,49.3,18772000.0,4.1,1560000.0,0.8,311000.0